version: '3.8'

services:
  web:
    build:
      context: .
      target: app-for-production
      args:
        app_name: ${APP_NAME}
        bundle_jobs: 8
        bundle_without: development:test
    env_file:
      - .env
    ports:
      - 80:80