default: &default
  adapter:  postgresql
  encoding: unicode
  host:     <%= ENV.fetch("DATABASE_HOST") { 'localhost' } %>
  port:     <%= ENV.fetch("DATABASE_PORT") { '5432' } %>
  username: <%= ENV.fetch("DATABASE_USER") { 'postgres' } %>
  password: <%= ENV.fetch("DATABASE_PASSWORD") { 'password' } %>
  pool:     <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

aws_rds: &aws_rds
  <<: *default
  database: <%= ENV.fetch('RDS_DB_NAME') %>
  username: <%= ENV.fetch('RDS_USERNAME') %>
  password: <%= ENV.fetch('RDS_PASSWORD') %>
  host: <%= ENV.fetch('RDS_HOSTNAME') %>
  port: <%= ENV.fetch('RDS_PORT') %>

development:
  <<: *default
  database: 'app_development'

test:
  <<: *default
  database: 'app_test'

staging:
  <<: *aws_rds

production:
  <<: *aws_rds
